# Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Копіюємо файли залежностей
COPY package*.json ./
COPY prisma ./prisma/

# Встановлюємо залежності
RUN npm install

# Генеруємо Prisma client
RUN npx prisma generate

# Копіюємо вихідний код
COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]